name: 'elementum'
services:
  elementum:
    image: elementum
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ELEMENTUM_VERSION: ${ELEMENTUM_VERSION}
        ELEMENTUM_ARCH: ${ELEMENTUM_ARCH}
    environment:
      - "TZ=${TZ}"
    network_mode: "host"
    volumes:
      - ${ELEMENTUM_DOWNLOADS}:/home/ubuntu/elementum_downloads/
      - ${ELEMENTUM_DATA}:/home/ubuntu/elementum_data/
    command:
      - -disableLibrarySync=${DISABLE_LIBRARY_SYNC}
      - -remoteHost=${REMOTE_IP}
      #- -remotePort=${REMOTE_PORT}
      #- -localHost=${LOCAL_IP}
      #- -localPort=${LOCAL_PORT}
      #- -listenInterfaces=${LIBTORRENT_LISTEN_INTERFACES}
      #- -outgoingInterfaces=${LIBTORRENT_OUTGOING_INTERFACES}
      #- -localLogin=${ELEMENTUM_LOGIN}
      #- -localPassword=${ELEMENTUM_PASSWORD}
    restart: unless-stopped
